language: python
python:
  - "3.5"
before_install:
  - "sudo apt-get install -y gfortran"
install:
  - "pip install -r requirements.txt"
  - "pip install python-coveralls"
before_script:
  - "python3 setup.py"
script:
  - "coverage-3.5 run ./code/test.py"
branches:
  only:
    - master
after_success:
  - coveralls --data_file=.coverage --config_file=.coveragerc
